spring:
  profiles:
    active:
    - dev
  application:
    name: PAYMENT

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
      enabled: false

   instance:
    hostname: localhost         
         